### ISSUE TITLE
MacOS: Working with Matplotlib in Virtual environment

### ISSUE THREAD

**Issue by RunzheYang** [TomoyaKung/DLCourse_AS#3]
在MacOS上如果在virtual environment下工作，会提示：
<img width="1280" alt="screen shot 2016-10-14 at 9 32 13 pm" src="https://cloud.githubusercontent.com/assets/13513972/19392376/1e46250c-9263-11e6-81ad-69f6b51f08d4.png">

这时候需要做一些 [workaround](http://matplotlib.org/faq/virtualenv_faq.html)
我尝试了start_ipython_osx.sh，但是会在import matplotlib.pyplot as plt的时候卡住。
<img width="1280" alt="screen shot 2016-10-14 at 9 11 31 pm" src="https://cloud.githubusercontent.com/assets/13513972/19392389/2900d488-9263-11e6-81e5-a5cc07cf3681.png">

**Comment by RunzheYang** [comment]
常成学长提供了另一种解决方案，[见这里](http://stackoverflow.com/questions/29433824/unable-to-import-matplotlib-pyplot-as-plt-in-virtualenv)。

这种方案是把backend改成TkAgg，我亲测可行。

**Comment by TomoyaKung** [comment]
关于 “working with matplotlib in vertual environments” 的相关问题可以先到 [http://matplotlib.org/faq/virtualenv_faq.html](http://matplotlib.org/faq/virtualenv_faq.html) 尝试一下不同的解决方案。比如这里面说：

> In regular virtualenv environment various workarounds exist. Some of these are given here:
> 
> The TKAgg backend doesn’t require any external dependencies and is normally always available.
> The QT4 framework PySide is pip installable.
> The upcoming [WX Phoenix](http://wiki.wxpython.org/ProjectPhoenix) toolkit is pip installable.

对backend的解释和如何修改可以参考 [http://matplotlib.org/faq/usage_faq.html#what-is-a-backend](http://matplotlib.org/faq/usage_faq.html#what-is-a-backend)
