### ISSUE TITLE
python-dev and other dependencies

### ISSUE THREAD

**Issue by niconiconi** [TomoyaKung/DLCourse_AS#4]
Someone may have problem when compiling numpy, since it need python-dev

`sudo apt-get install python-dev`

**Comment by niconiconi** [comment]
scipy needs

`sudo apt-get install gfortran liblapack-dev`

**Comment by cloudygoose** [comment]
I guess this is a helping note instead of a question?
If that's the case, then thanks, and maybe you can close this issue?
